[phases.setup]
nixPkgs = ["nodejs_24"]
nixpkgsArchive = "cf93ceb06388f5714302b702cccf2c77f6064442"
aptPkgs = ["curl", "wget"]

[phases.install]
cmds = [
	"npm exec --yes pnpm@11.5.3 -- pnpm i --frozen-lockfile",
]

[phases.build]
cmds = ["npm exec --yes pnpm@11.5.3 -- pnpm run build"]

[start]
cmd = "node ./build/index.js"
