packages:
  - .

minimumReleaseAge: 2880

allowBuilds:
  '@tailwindcss/oxide': true
  better-sqlite3: true
  esbuild: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
